class CarModel {
  final String brand;
  final String model;
  final String modelUrl;
  final String model3dUrl;
  final String rating;
  final String rate;
  final String speed;
  final String engine;
  final String seats;

  CarModel({
    required this.brand,
    required this.model,
    required this.modelUrl,
    required this.model3dUrl,
    required this.rating,
    required this.rate,
    required this.speed,
    required this.engine,
    required this.seats,
  });
}

List<CarModel> cars = [
  CarModel(
    brand: 'Ferrari',
    model: '488 Pista Spider',
    modelUrl: 'assets/cars/spider.png',
    model3dUrl: 'assets/3Dmodels/ferrari.glb',
    rating: '4.9',
    rate: '6000',
    speed: '340 Km/h',
    engine: '3.9L V8',
    seats: '2',
  ),
  CarModel(
    brand: 'Ford',
    model: 'Mustang GT',
    modelUrl: 'assets/cars/mustang.png',
    model3dUrl: 'assets/3Dmodels/ferrari.glb',
    rating: '4.7',
    rate: '3000',
    speed: '250 Km/h',
    engine: '5.0L V8',
    seats: '2',
  ),
  CarModel(
    brand: 'Lamborghini',
    model: 'Huracan',
    modelUrl: 'assets/cars/huracan.png',
    model3dUrl: 'assets/3Dmodels/ferrari.glb',
    rating: '4.8',
    rate: '6000',
    speed: '325 Km/h',
    engine: '5.2L V10',
    seats: '2',
  ),
  CarModel(
    brand: 'Lamborghini',
    model: 'Urus',
    modelUrl: 'assets/cars/urus.png',
    model3dUrl: 'assets/3Dmodels/ferrari.glb',
    rating: '4.7',
    rate: '5000',
    speed: '305 Km/h',
    engine: '4.0L V8',
    seats: '4',
  ),
  CarModel(
    brand: 'BMW',
    model: 'M4 Sports',
    modelUrl: 'assets/cars/M4.png',
    model3dUrl: 'assets/3Dmodels/ferrari.glb',
    rating: '4.9',
    rate: '3000',
    speed: '290 Km/h',
    engine: '3.0L Inline-6',
    seats: '2',
  ),
  CarModel(
    brand: 'Lamborghini',
    model: 'LP 740',
    modelUrl: 'assets/cars/lp740.png',
    model3dUrl: 'assets/3Dmodels/ferrari.glb',
    rating: '4.9',
    rate: '5000',
    speed: '350 Km/h',
    engine: '6.5L NA V12',
    seats: '2',
  ),
  CarModel(
    brand: 'Mercedes',
    model: 'C63',
    modelUrl: 'assets/cars/C63.png',
    model3dUrl: 'assets/3Dmodels/ferrari.glb',
    rating: '4.7',
    rate: '2000',
    speed: '290 Km/h',
    engine: '4.0L V8',
    seats: '4',
  ),
  CarModel(
    brand: 'Porsche',
    model: '911 Carrera',
    modelUrl: 'assets/cars/911.png',
    model3dUrl: 'assets/3Dmodels/ferrari.glb',
    rating: '4.8',
    rate: '4000',
    speed: '293 Km/h',
    engine: '3.0L Flat-6',
    seats: '2',
  ),
  CarModel(
    brand: 'Audi',
    model: 'RS5',
    modelUrl: 'assets/cars/rs5.png',
    model3dUrl: 'assets/3Dmodels/ferrari.glb',
    rating: '4.7',
    rate: '3000',
    speed: '280 Km/h',
    engine: '2.9L V6',
    seats: '4',
  ),
  CarModel(
    brand: 'Chevrolet',
    model: 'Corvette Z06',
    modelUrl: 'assets/cars/z06.png',
    model3dUrl: 'assets/3Dmodels/ferrari.glb',
    rating: '4.6',
    rate: '2000',
    speed: '315 Km/h',
    engine: '5.5L NA V8',
    seats: '2',
  ),
  CarModel(
    brand: 'Honda',
    model: 'Civic Type R',
    modelUrl: 'assets/cars/typeR.png',
    model3dUrl: 'assets/3Dmodels/ferrari.glb',
    rating: '4.5',
    rate: '2000',
    speed: '272 Km/h',
    engine: '2.0L Inline-4',
    seats: '4',
  ),
  CarModel(
    brand: 'Chevrolet',
    model: 'Corvette Stingray',
    modelUrl: 'assets/cars/corvette.png',
    model3dUrl: 'assets/3Dmodels/ferrari.glb',
    rating: '4.8',
    rate: '4000',
    speed: '312 Km/h',
    engine: '6.2L NA V8',
    seats: '2',
  ),
];
